controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.05
  escape_vel: -0.1
  max_vel_theta: 1.57
  min_vel_theta: -1.57

  min_in_place_vel_theta: 0.157

  acc_lim_theta: 3.14
  acc_lim_x: 0.7
  acc_lim_y: 0.0

  sim_time: 2.0
  sim_granularity: 0.05

  vx_samples: 10.0
  vtheta_samples: 15.0

  path_distance_bias: 4
  goal_distance_bias: 3
  occdist_scale: 0.07

  holonomic_robot: false
