controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.02
  escape_vel: -0.1
  max_vel_theta: 2.36
  min_vel_theta: -2.36
  min_in_place_vel_theta: 0.236

  acc_lim_theta: 4.72
  acc_lim_x: 0.4
  acc_lim_y: 0.0

  sim_time: 2.0
  sim_granularity: 0.05

  vx_samples: 10.0
  vtheta_samples: 20.0
  heading_lookahead: 2.0

  meter_scoring: true
  pdist_scale: 2
  gdist_scale: 4
  occdist_scale: 0.07
  oscillation_reset_dist: 0.01

  holonomic_robot: false
