controller_frequency: 10
planner_frequency: 1

TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.02
  escape_vel: -0.1
  max_vel_theta: 2.36
  min_vel_theta: -2.36
  min_in_place_vel_theta: 0.236

  acc_lim_theta: 4.72
  acc_lim_x: 0.8
  acc_lim_y: 0.0

  sim_time: 1.0
  sim_granularity: 0.015

  vx_samples: 15.0
  vtheta_samples: 20.0
  heading_lookahead: 1.0

  meter_scoring: true
  pdist_scale: 0.7
  gdist_scale: 0.1
  occdist_scale: 0.01
  oscillation_reset_dist: 0.01
  escape_reset_dist: 0.015
  escape_reset_theta: 0.5

  holonomic_robot: false
